import React from "react";
import Head from "next/head";

export default function about() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>my about</h1>
    </>
  );
}
