import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ChangeTitle by github</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>My home</h1>
    </>
  );
}
